# Generated by Django 5.2.3 on 2025-07-02 19:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativaTransporte',
            fields=[
                ('id_cooperativa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('informacion_contacto', models.CharField(max_length=255)),
                ('n_vehiculos', models.IntegerField()),
                ('color_vehiculo', models.CharField(max_length=50)),
                ('monto_a_cobrar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=16, unique=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='Inactiva', max_length=10)),
                ('saldo_asociado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('codigo_seguridad', models.CharField(default='000', max_length=3, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RecargaSaldo',
            fields=[
                ('id_recarga', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('id_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='PagoPasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cooperativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TransPorto.cooperativatransporte')),
                ('id_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('detalles_de_ruta', models.CharField(max_length=150)),
                ('id_cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.cooperativatransporte')),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id_rutas', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('hora', models.TimeField()),
                ('id_cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.cooperativatransporte')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.unidadtransporte')),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_licencia', models.CharField(max_length=20)),
                ('informacion_contacto', models.CharField(max_length=255)),
                ('id_cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.cooperativatransporte')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.unidadtransporte')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
