# Generated by Django 5.2.3 on 2025-07-03 01:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.cooperativatransporte')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransPorto.tarjeta')),
            ],
        ),
    ]
