# Generated by Django 5.2.3 on 2025-07-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0002_qrcodepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tema_preferido',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_telefonico',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QRCodePago',
        ),
    ]
