# Generated by Django 5.2.3 on 2025-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0003_cliente_tema_preferido_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='orden_botones_inicio',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
