# Generated by Django 5.2.3 on 2025-08-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0004_cliente_orden_botones_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_rostro',
            field=models.ImageField(blank=True, null=True, upload_to='rostros/'),
        ),
    ]
