# Generated by Django 5.2.3 on 2025-08-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0005_cliente_foto_rostro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagopasaje',
            name='cantidad_pasajes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pagopasaje',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
