# Generated by Django 5.2.3 on 2025-08-11 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0006_pagopasaje_cantidad_pasajes_alter_pagopasaje_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagopasaje',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagopasaje',
            name='id_cooperativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TransPorto.cooperativatransporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagopasaje',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
