# Generated by Django 5.2.3 on 2025-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0007_alter_pagopasaje_fecha_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagopasaje',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='encoding_facial',
            field=models.TextField(blank=True, help_text='Encoding facial codificado en base64', null=True),
        ),
        migrations.AddField(
            model_name='pagopasaje',
            name='id_pago',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='codigo_seguridad',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
    ]
