# Generated by Django 5.2.3 on 2025-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0008_remove_pagopasaje_id_cliente_encoding_facial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='encoding_facial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
