# Generated by Django 5.2.3 on 2025-08-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0009_alter_cliente_encoding_facial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductores',
            name='id_conductor',
        ),
        migrations.RemoveField(
            model_name='cooperativatransporte',
            name='id_cooperativa',
        ),
        migrations.RemoveField(
            model_name='pagopasaje',
            name='id_pago',
        ),
        migrations.RemoveField(
            model_name='recargasaldo',
            name='id_recarga',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='id_rutas',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='id_tarjeta',
        ),
        migrations.RemoveField(
            model_name='unidadtransporte',
            name='id_unidad',
        ),
        migrations.AddField(
            model_name='conductores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='cooperativatransporte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pagopasaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='recargasaldo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='rutas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
