# Generated by Django 5.2.3 on 2025-08-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0010_remove_conductores_id_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductores',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cooperativatransporte',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pagopasaje',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recargasaldo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unidadtransporte',
            name='id',
        ),
        migrations.AddField(
            model_name='conductores',
            name='id_conductor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cooperativatransporte',
            name='id_cooperativa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pagopasaje',
            name='id_pago',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='recargasaldo',
            name='id_recarga',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rutas',
            name='id_rutas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_tarjeta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='id_unidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
