# Generated by Django 5.2.3 on 2025-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0011_remove_conductores_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagopasaje',
            name='id_pago',
        ),
        migrations.AddField(
            model_name='pagopasaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='codigo_seguridad',
            field=models.CharField(default='000', max_length=3, unique=True),
        ),
    ]
