# Generated by Django 5.2.3 on 2025-08-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0012_remove_pagopasaje_id_pago_pagopasaje_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='encoding_facial',
        ),
    ]
